// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// RendererMock is an autogenerated mock type for the Renderer type
type RendererMock struct {
	mock.Mock
}

// Render provides a mock function with given fields: _a0
func (_m *RendererMock) Render(_a0 interface{}) {
	_m.Called(_a0)
}

type mockConstructorTestingTNewRendererMock interface {
	mock.TestingT
	Cleanup(func())
}

// NewRendererMock creates a new instance of RendererMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRendererMock(t mockConstructorTestingTNewRendererMock) *RendererMock {
	mock := &RendererMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
