// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// RendererMock is an autogenerated mock type for the Renderer type
type RendererMock struct {
	mock.Mock
}

// Render provides a mock function with given fields: _a0
func (_m *RendererMock) Render(_a0 interface{}) (string, error) {
	ret := _m.Called(_a0)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(interface{}) (string, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(interface{}) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRendererMock interface {
	mock.TestingT
	Cleanup(func())
}

// NewRendererMock creates a new instance of RendererMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRendererMock(t mockConstructorTestingTNewRendererMock) *RendererMock {
	mock := &RendererMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
