name: CI/CD
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
#  golangci:
#    name: lint
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: golangci-lint
#        uses: golangci/golangci-lint-action@v2
  test:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.head_commit.message), '[skip-ci]')"
    steps:
      - uses: actions/checkout@v2
      - name: 'Load Cache Keys'
        uses: actions/cache@v2 # Create directory for cache
        id: cache
        with:
          path: docker-cache
          key: ${{ runner.os }}-docker-tests-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-tests-
      - name: 'Load docker layers'
        run: |
          ./scripts/load-docker-cache.sh test
      - name: 'Build image' # build image (using cache from previous steps) and build new cache to cache dir
        run: |
          docker-compose build tests
          ./scripts/save-docker-cache.sh my-app test
      - name: 'Run tests'
        run: make compose-tests
      - name: 'Down docker containers'
        run: make compose-down